package dev.code93.kmp.qrd.data

import dev.code93.kmp.qrd.SubFieldType

/**
 * Section III of the EASPBV standard — additional merchant information,
 * Colombian tax fields and the transaction consecutive.
 *
 * @property merchantCategoryCode Merchant Category Code (tag `52`), per ISO 18245.
 * @property countryCode Country code (tag `58`), ISO 3166-1 alpha-2; `"CO"` by default.
 * @property merchantName Merchant name (tag `59`, up to 25 chars).
 * @property merchantCity Merchant city (tag `60`, up to 15 chars).
 * @property postalCode Postal code for geo-referencing (tag `61`).
 * @property channel Channel that generated the QR (tag `80`, sub-tag `01`):
 *   `IM` (manual POS), `POS`, `APP` (mobile banking), `ECOMM` (internet),
 *   `MPOS`, `ATM`, `CB` (banking correspondent), `OFC` (branch office).
 * @property taxIvaCondition IVA condition (tag `81`): `"01"` wallet-generated,
 *   `"02"` merchant-calculated, `"03"` wallet must compute the percentage
 *   (if `"03"` and the IVA value is zero, the merchant does not support IVA).
 * @property taxIvaValue IVA value or percentage (tag `82`).
 * @property taxIvaBase IVA base amount (tag `83`).
 * @property taxIncCondition INC (consumption tax) condition (tag `84`); same semantics as [taxIvaCondition].
 * @property taxIncValue INC value or percentage (tag `85`).
 * @property transactionId Transaction consecutive / TRXID (tag `90`, sub-tag `01`).
 *   Generated by the network for dynamic QRs; `"000000"` for static QRs. For
 *   Bre-B instant payments the ID is up to 19 characters. QRs issued under
 *   pre-1.4 spec versions carried it in tag `86`, which the decoder still
 *   reads as a fallback.
 */
@ConsistentCopyVisibility
public data class AdditionalMerchantInformationData internal constructor(
    public val merchantCategoryCode: String,
    public val countryCode: String,
    public val merchantName: String,
    public val merchantCity: String,
    public val postalCode: String?,
    public val channel: String?,
    public val taxIvaCondition: String?,
    public val taxIvaValue: String?,
    public val taxIvaBase: String?,
    public val taxIncCondition: String?,
    public val taxIncValue: String?,
    public val transactionId: String?
)

/** Sub-fields of the channel template (tag `80`). */
public enum class ChannelType(override val subTag: String) : SubFieldType {
    /** Globally Unique Identifier (`CO.COM.RBM.CANAL` / `CO.COM.CRB.CANAL`). */
    GUID("00"),

    /** Channel value: `IM`, `POS`, `APP`, `ECOMM`, `MPOS`, `ATM`, `CB`, `OFC`. */
    CHANNEL_VALUE("01")
}

/** Sub-fields of the IVA condition template (tag `81`). */
public enum class TaxIvaConditionType(override val subTag: String) : SubFieldType {
    /** Globally Unique Identifier (`CO.COM.RBM.CIVA` / `CO.COM.CRB.CIVA`). */
    GUID("00"),

    /** `01` wallet-generated, `02` merchant-calculated, `03` wallet computes the percentage. */
    VALUE("01")
}

/** Sub-fields of the IVA value template (tag `82`). */
public enum class TaxIvaValueType(override val subTag: String) : SubFieldType {
    /** Globally Unique Identifier (`CO.COM.RBM.IVA` / `CO.COM.CRB.IVA`). */
    GUID("00"),

    /** IVA value or percentage. */
    VALUE("01")
}

/** Sub-fields of the IVA base template (tag `83`). */
public enum class TaxIvaBaseType(override val subTag: String) : SubFieldType {
    /** Globally Unique Identifier (`CO.COM.RBM.BASE` / `CO.COM.CRB.BASE`). */
    GUID("00"),

    /** IVA base amount. */
    BASE_VALUE("01")
}

/** Sub-fields of the INC condition template (tag `84`). */
public enum class IncConditionType(override val subTag: String) : SubFieldType {
    /** Globally Unique Identifier (`CO.COM.RBM.CINC` / `CO.COM.CRB.CINC`). */
    GUID("00"),

    /** `01` wallet-generated, `02` merchant-calculated, `03` wallet computes the percentage. */
    VALUE("01")
}

/** Sub-fields of the INC value template (tag `85`). */
public enum class IncValueType(override val subTag: String) : SubFieldType {
    /** Globally Unique Identifier (`CO.COM.RED.INC` / `CO.COM.CRB.INC`). */
    GUID("00"),

    /** INC value or percentage. */
    VALUE("01")
}

/** Sub-fields of the transaction consecutive template (tag `90`). */
public enum class TransactionIdType(override val subTag: String) : SubFieldType {
    /** Globally Unique Identifier (`CO.COM.RED.TRXID`). */
    GUID("00"),

    /** Transaction ID (max 19 characters for Bre-B instant payments). */
    TRANSACTION_ID("01")
}
